In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame()
df = pd.read_csv("train_proper_csv_attack_types.csv",header = None)
df = df.rename(columns=df.iloc[0])
df = df.drop(df.index[0])
df = df.drop('unknown2',axis=1)

C:\Users\Nishant\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (0,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,42) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
df1 = pd.DataFrame()
df1 = pd.read_csv("test_proper_csv_attack_types.csv",header = None)
df1 = df1.rename(columns=df1.iloc[0])
df1 = df1.drop(df1.index[0])
df1 = df1.drop('unknown2',axis=1)

C:\Users\Nishant\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (0,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,42) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [4]:
df_tot = pd.concat([df,df1])
df_tot.head()

duration protocol_type   service flag src_bytes dst_bytes land  \
1        0           tcp  ftp_data   SF       491         0    0   
2        0           udp     other   SF       146         0    0   
3        0           tcp   private   S0         0         0    0   
4        0           tcp      http   SF       232      8153    0   
5        0           tcp      http   SF       199       420    0   

  wrong_fragment urgent hot   ...    dst_host_srv_count  \
1              0      0   0   ...                    25   
2              0      0   0   ...                     1   
3              0      0   0   ...                    26   
4              0      0   0   ...                   255   
5              0      0   0   ...                   255   

  dst_host_same_srv_rate dst_host_diff_srv_rate dst_host_same_src_port_rate  \
1                   0.17                   0.03                        0.17   
2                    0.0                    0.6                        0.88   
3                    0.1                   0.05                         0.0   
4                    1.0                    0.0                        0.03   
5                    1.0                    0.0                         0.0   

  dst_host_srv_diff_host_rate dst_host_serror_rate dst_host_srv_serror_rate  \
1                         0.0                  0.0                      0.0   
2                         0.0                  0.0                      0.0   
3                         0.0                  1.0                      1.0   
4                        0.04                 0.03                     0.01   
5                         0.0                  0.0                      0.0   

  dst_host_rerror_rate dst_host_srv_rerror_rate unknown1  
1                 0.05                      0.0   normal  
2                  0.0                      0.0   normal  
3                  0.0                      0.0      dos  
4                  0.0                     0.01   normal  
5                  0.0                      0.0   normal  

[5 rows x 42 columns]

In [5]:
df_tot.shape

(148516, 42)

In [6]:
df_tot['label']=df_tot['unknown1']
df_tot.head()

duration protocol_type   service flag src_bytes dst_bytes land  \
1        0           tcp  ftp_data   SF       491         0    0   
2        0           udp     other   SF       146         0    0   
3        0           tcp   private   S0         0         0    0   
4        0           tcp      http   SF       232      8153    0   
5        0           tcp      http   SF       199       420    0   

  wrong_fragment urgent hot   ...   dst_host_same_srv_rate  \
1              0      0   0   ...                     0.17   
2              0      0   0   ...                      0.0   
3              0      0   0   ...                      0.1   
4              0      0   0   ...                      1.0   
5              0      0   0   ...                      1.0   

  dst_host_diff_srv_rate dst_host_same_src_port_rate  \
1                   0.03                        0.17   
2                    0.6                        0.88   
3                   0.05                         0.0   
4                    0.0                        0.03   
5                    0.0                         0.0   

  dst_host_srv_diff_host_rate dst_host_serror_rate dst_host_srv_serror_rate  \
1                         0.0                  0.0                      0.0   
2                         0.0                  0.0                      0.0   
3                         0.0                  1.0                      1.0   
4                        0.04                 0.03                     0.01   
5                         0.0                  0.0                      0.0   

  dst_host_rerror_rate dst_host_srv_rerror_rate unknown1   label  
1                 0.05                      0.0   normal  normal  
2                  0.0                      0.0   normal  normal  
3                  0.0                      0.0      dos     dos  
4                  0.0                     0.01   normal  normal  
5                  0.0                      0.0   normal  normal  

[5 rows x 43 columns]

In [7]:
df_tot=df_tot.drop(['unknown1'],axis=1)

In [8]:
df_tot

duration protocol_type     service  flag src_bytes dst_bytes land  \
1            0           tcp    ftp_data    SF       491         0    0   
2            0           udp       other    SF       146         0    0   
3            0           tcp     private    S0         0         0    0   
4            0           tcp        http    SF       232      8153    0   
5            0           tcp        http    SF       199       420    0   
6            0           tcp     private   REJ         0         0    0   
7            0           tcp     private    S0         0         0    0   
8            0           tcp     private    S0         0         0    0   
9            0           tcp  remote_job    S0         0         0    0   
10           0           tcp     private    S0         0         0    0   
11           0           tcp     private   REJ         0         0    0   
12           0           tcp     private    S0         0         0    0   
13           0           tcp        http    SF       287      2251    0   
14           0           tcp    ftp_data    SF       334         0    0   
15           0           tcp        name    S0         0         0    0   
16           0           tcp  netbios_ns    S0         0         0    0   
17           0           tcp        http    SF       300     13788    0   
18           0          icmp       eco_i    SF        18         0    0   
19           0           tcp        http    SF       233       616    0   
20           0           tcp        http    SF       343      1178    0   
21           0           tcp         mtp    S0         0         0    0   
22           0           tcp     private    S0         0         0    0   
23           0           tcp        http    SF       253     11905    0   
24        5607           udp       other    SF       147       105    0   
25           0           tcp         mtp    S0         0         0    0   
26         507           tcp      telnet    SF       437     14421    0   
27           0           tcp     private    S0         0         0    0   
28           0           tcp        http    SF       227      6588    0   
29           0           tcp        http    SF       215     10499    0   
30           0           tcp        http    SF       241      1400    0   
...        ...           ...         ...   ...       ...       ...  ...   
22514        0           udp       other    SF       115         0    0   
22515        0           tcp        http    S0         0         0    0   
22516        0           tcp        http    SF       322       396    0   
22517     7498           tcp      telnet    SF         0        44    0   
22518        0           tcp        http    SF       295       757    0   
22519     8209           tcp      telnet    SF         0        15    0   
22520        0           tcp     private   REJ         0         0    0   
22521        0           udp     private    SF         1         1    0   
22522        0           tcp        http    SF     54540      8314    0   
22523        0           tcp        http    SF       289      9522    0   
22524       15           tcp         ftp    SF        45       214    0   
22525     2064           tcp        http  RSTR     55744         0    0   
22526        0           tcp        http    SF       169      4997    0   
22527        0           tcp        http    SF       236     16257    0   
22528        0          icmp       ecr_i    SF      1032         0    0   
22529        0           tcp      finger    SF         9       139    0   
22530        0           tcp     private    S0         0         0    0   
22531        0           tcp     private    S0         0         0    0   
22532        0           tcp        http    SF       264     14839    0   
22533        0           tcp        http    SF       274      1623    0   
22534        0           tcp     private   REJ         0         0    0   
22535        0           tcp   

In [9]:
df_tot.label.unique()

array(['normal', 'dos', 'r2l', 'probe', 'u2r', 'unknown'], dtype=object)

In [10]:
#delete unknown attack and normal
#df_tot=df_tot[df_tot.label!='unknown']
#df_tot=df_tot[df_tot.label!='normal']

In [11]:
#df_tot.label.unique()

array(['dos', 'r2l', 'probe', 'u2r'], dtype=object)

In [10]:
df_tot.shape

(148516, 42)

In [11]:
print(df_tot[df_tot.label=='dos'].shape[0])

51668


In [12]:
print(df_tot[df_tot.label=='u2r'].shape[0])

89


In [13]:
print(df_tot[df_tot.label=='r2l'].shape[0])

3194


In [14]:
print(df_tot[df_tot.label=='probe'].shape[0])

12762


In [15]:
print(df_tot[df_tot.label=='normal'].shape[0])

77053


In [16]:
print(df_tot[df_tot.label=='unknown'].shape[0])

3750


In [17]:
#seperate feature and response
df_x=df_tot.drop('label',axis=1)
df_y=df_tot['label']

In [18]:
print(df_x.shape,df_y.shape)

(148516, 41) (148516,)


In [26]:
def bool_attack1(x):
    if(x != "normal"):
        return "attack"
    else:
        return "normal"

In [27]:
def bool_attack(x):
    if(x == "dos"):
        return 0
    elif(x == "probe"):
        return 1
    elif(x == "r2l"):
        return 2
    else:
        return 3

In [28]:
#apply on df_y
df_output_attack=df_y.apply(bool_attack1)

In [29]:
df_output_attack.shape

(148516,)

In [30]:
df_x.head()

duration protocol_type   service flag src_bytes dst_bytes land  \
1        0           tcp  ftp_data   SF       491         0    0   
2        0           udp     other   SF       146         0    0   
3        0           tcp   private   S0         0         0    0   
4        0           tcp      http   SF       232      8153    0   
5        0           tcp      http   SF       199       420    0   

  wrong_fragment urgent hot           ...            dst_host_count  \
1              0      0   0           ...                       150   
2              0      0   0           ...                       255   
3              0      0   0           ...                       255   
4              0      0   0           ...                        30   
5              0      0   0           ...                       255   

  dst_host_srv_count dst_host_same_srv_rate dst_host_diff_srv_rate  \
1                 25                   0.17                   0.03   
2                  1                    0.0                    0.6   
3                 26                    0.1                   0.05   
4                255                    1.0                    0.0   
5                255                    1.0                    0.0   

  dst_host_same_src_port_rate dst_host_srv_diff_host_rate  \
1                        0.17                         0.0   
2                        0.88                         0.0   
3                         0.0                         0.0   
4                        0.03                        0.04   
5                         0.0                         0.0   

  dst_host_serror_rate dst_host_srv_serror_rate dst_host_rerror_rate  \
1                  0.0                      0.0                 0.05   
2                  0.0                      0.0                  0.0   
3                  1.0                      1.0                  0.0   
4                 0.03                     0.01                  0.0   
5                  0.0                      0.0                  0.0   

  dst_host_srv_rerror_rate  
1                      0.0  
2                      0.0  
3                      0.0  
4                     0.01  
5                      0.0  

[5 rows x 41 columns]

In [31]:
#preprocessing against 4 classes
from sklearn.feature_selection import SelectFpr
from sklearn.feature_selection import chi2
from sklearn.preprocessing import Normalizer
df_tot_dummies = pd.get_dummies(df_x,columns = ["protocol_type","service","flag"])
x_normalise = Normalizer().fit(df_tot_dummies)
df_tot_dummies = x_normalise.transform(df_tot_dummies)
x_new = SelectFpr(chi2, alpha=0.05).fit_transform(df_tot_dummies, df_output_attack)

C:\Users\Nishant\Anaconda3\lib\site-packages\sklearn\feature_selection\univariate_selection.py:560: RuntimeWarning: invalid value encountered in less
  return self.pvalues_ < self.alpha


In [32]:
x_new.shape

(148516, 36)

In [42]:
x_new

array([[0.95521304, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.49636852, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.0035164 ,
        0.        ],
       ...,
       [0.98855875, 0.15069449, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.11555127, 0.11555127, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [38]:
df_output=df_y.reset_index(drop=True)

In [43]:
df_output

0          normal
1          normal
2             dos
3          normal
4          normal
5             dos
6             dos
7             dos
8             dos
9             dos
10            dos
11            dos
12         normal
13            r2l
14            dos
15            dos
16         normal
17          probe
18         normal
19         normal
20            dos
21            dos
22         normal
23         normal
24            dos
25         normal
26            dos
27         normal
28         normal
29         normal
           ...   
148486     normal
148487    unknown
148488     normal
148489    unknown
148490     normal
148491    unknown
148492      probe
148493      probe
148494        dos
148495     normal
148496        u2r
148497    unknown
148498     normal
148499     normal
148500        dos
148501     normal
148502        dos
148503        dos
148504     normal
148505     normal
148506        dos
148507     normal
148508        dos
148509    unknown
148510    

In [41]:
x_new[0]

array([9.55213037e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       3.89088814e-03, 3.89088814e-03, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       2.91816610e-01, 4.86361017e-02, 5.83633220e-05, 3.30725492e-04,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 9.72722034e-05,
       0.00000000e+00, 0.00000000e+00, 1.94544407e-03, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [44]:
index_normal=list((df_output.loc[df_output.values=='normal'].index))
index_unknown=list((df_output.loc[df_output.values=='unknown'].index))

In [46]:
index_total=index_normal+index_unknown

In [47]:
len(index_total)

80803

In [48]:
#delete normal and unknown from label
df_output=df_output[df_output.values!='normal']
df_output=df_output[df_output.values!='unknown']

In [50]:
df_output.shape

(67713,)

In [51]:
#apply bool_attack
df_output=df_output.apply(bool_attack)

In [54]:
#delete corresponding row from x_new
#x = numpy.delete(x, (0), axis=0)
import numpy as np
x_new=np.delete(x_new,index_total,axis=0)

In [56]:
x_new.shape

(67713, 36)

In [57]:
#divide training and testing data
X_train = x_new[:58630]
y_train = df_output.iloc[:58630]
X_test = x_new[58630:]
y_test = df_output.iloc[58630:]

In [58]:
print(X_train.shape,y_train.shape,X_test.shape,y_test.shape)

(58630, 36) (58630,) (9083, 36) (9083,)


In [63]:
#train your classifier and classify
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=10)
y_score = rf.fit(X_train,y_train)

#predict
y_pred = rf.predict(X_test)
y_pred_prob = rf.predict_proba(X_test)[::,0]
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
C = confusion_matrix(y_test,y_pred)

             precision    recall  f1-score   support

          0       1.00      0.99      1.00      5741
          1       0.48      1.00      0.65      1106
          2       0.99      0.45      0.62      2199
          3       0.26      0.41      0.32        37

avg / total       0.93      0.86      0.86      9083



In [64]:
C

array([[5703,   38,    0,    0],
       [   0, 1106,    0,    0],
       [   7, 1157,  993,   42],
       [   3,    4,   15,   15]], dtype=int64)

In [65]:
def perf_measure_class(C, i):
    TP = C[i, i] 
    FP = np.sum(C, axis=0)[i] - C[i, i]  #The corresponding column for class_i - TP
    FN = np.sum(C, axis=1)[i] - C[i, i] # The corresponding row for class_i - TP
    TN = np.sum(C) - TP -FP -FN
    acc = (TP+TN)/(TP+TN+FP+FN)
    fpr = (FP)/(FP+TN)
    dr = (TP)/(TP+FN)
    
    return fpr, acc, dr

In [66]:
for i in range(4):
    fpr, acc, dr = perf_measure_class(C, i)
    print("class "+str(i)+": "+"fpr: "+str(fpr)+" acc: "+str(acc)+" dr: "+str(dr))


class 0: fpr: 0.002992220227408737 acc: 0.994715402400088 dr: 0.9933809440863961
class 1: fpr: 0.15030713300739626 acc: 0.8679951557855334 dr: 1.0
class 2: fpr: 0.002178965717606043 acc: 0.8655730485522405 dr: 0.451568894952251
class 3: fpr: 0.004642936104355516 acc: 0.9929538698667841 dr: 0.40540540540540543


In [95]:
from sklearn.ensemble import AdaBoostClassifier
ada = AdaBoostClassifier()
ada.fit(X_train,y_train)

#predict
y_pred = ada.predict(X_test)
y_pred_prob = ada.predict_proba(X_test)[::,0]
print(classification_report(y_test,y_pred))
C = confusion_matrix(y_test,y_pred)

             precision    recall  f1-score   support

          0       0.77      1.00      0.87      5741
          1       0.66      0.57      0.61      1106
          2       0.96      0.29      0.45      2199
          3       0.00      0.00      0.00        37

avg / total       0.80      0.77      0.73      9083



In [96]:
C

array([[5719,   22,    0,    0],
       [ 479,  627,    0,    0],
       [1261,  292,  645,    1],
       [   5,    3,   29,    0]], dtype=int64)

In [97]:
for i in range(4):
    fpr, acc, dr = perf_measure_class(C, i)
    print("class "+str(i)+": "+"fpr: "+str(fpr)+" acc: "+str(acc)+" dr: "+str(dr))


class 0: fpr: 0.5221424296828246 acc: 0.8054607508532423 dr: 0.9961679149973872
class 1: fpr: 0.03973925034474113 acc: 0.9123637564681273 dr: 0.5669077757685352
class 2: fpr: 0.00421266705403835 acc: 0.825718374986238 dr: 0.2933151432469304
class 3: fpr: 0.00011054609772275039 acc: 0.995816360233403 dr: 0.0


In [103]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train,y_train)

y_pred = gnb.predict(X_test)
y_pred_prob = gnb.predict_proba(X_test)[::,0]
print(classification_report(y_test,y_pred))
C = confusion_matrix(y_test,y_pred)

             precision    recall  f1-score   support

          0       0.87      0.93      0.90      5741
          1       0.26      0.30      0.28      1106
          2       0.98      0.22      0.36      2199
          3       0.03      0.78      0.05        37

avg / total       0.82      0.68      0.69      9083



In [104]:
C

array([[5354,   28,    0,  359],
       [ 772,  334,    0,    0],
       [  21,  931,  488,  759],
       [   0,    0,    8,   29]], dtype=int64)

In [105]:
for i in range(4):
    fpr, acc, dr = perf_measure_class(C, i)
    print("class "+str(i)+": "+"fpr: "+str(fpr)+" acc: "+str(acc)+" dr: "+str(dr))


class 0: fpr: 0.23728306403351287 acc: 0.8700869756688319 dr: 0.9325901410904024
class 1: fpr: 0.12022063432368058 acc: 0.8094241990531763 dr: 0.30198915009041594
class 2: fpr: 0.0011621150493898896 acc: 0.8107453484531543 dr: 0.22191905411550705
class 3: fpr: 0.12359053725403493 acc: 0.8760321479687327 dr: 0.7837837837837838


In [110]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=10)
neigh.fit(X_train,y_train) 

y_pred = neigh.predict(X_test)
y_pred_prob = neigh.predict_proba(X_test)[::,0]
print(classification_report(y_test,y_pred))
C = confusion_matrix(y_test,y_pred)

             precision    recall  f1-score   support

          0       0.92      0.98      0.95      5741
          1       0.41      0.96      0.58      1106
          2       0.96      0.13      0.23      2199
          3       0.19      0.46      0.27        37

avg / total       0.86      0.77      0.73      9083



In [111]:
C

array([[5607,  130,    4,    0],
       [  41, 1065,    0,    0],
       [ 454, 1377,  294,   74],
       [   2,   10,    8,   17]], dtype=int64)

In [112]:
for i in range(4):
    fpr, acc, dr = perf_measure_class(C, i)
    print("class "+str(i)+": "+"fpr: "+str(fpr)+" acc: "+str(acc)+" dr: "+str(dr))


class 0: fpr: 0.14871334530221425 acc: 0.9305295607178246 dr: 0.9766591186204494
class 1: fpr: 0.19017174376331955 acc: 0.8284707695695255 dr: 0.9629294755877035
class 2: fpr: 0.0017431725740848344 acc: 0.7889463833535175 dr: 0.13369713506139155
class 3: fpr: 0.008180411231483529 acc: 0.9896509963668392 dr: 0.4594594594594595


In [118]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state=0)
dt.fit(X_train,y_train) 

y_pred = dt.predict(X_test)
y_pred_prob = dt.predict_proba(X_test)[::,0]
print(classification_report(y_test,y_pred))
C = confusion_matrix(y_test,y_pred)
for i in range(4):
    fpr, acc, dr = perf_measure_class(C, i)
    print("class "+str(i)+": "+"fpr: "+str(fpr)+" acc: "+str(acc)+" dr: "+str(dr))


             precision    recall  f1-score   support

          0       0.96      0.99      0.98      5741
          1       0.54      1.00      0.70      1106
          2       0.98      0.35      0.51      2199
          3       0.04      0.41      0.07        37

avg / total       0.91      0.83      0.83      9083

class 0: fpr: 0.06582884500299221 acc: 0.9685126059671915 dr: 0.9885037449921616
class 1: fpr: 0.11721198445530902 acc: 0.896840251018386 dr: 0.9981916817359855
class 2: fpr: 0.002324230098779779 acc: 0.8400308268193328 dr: 0.34652114597544337
class 3: fpr: 0.03935441078929914 acc: 0.9583837939006936 dr: 0.40540540540540543


In [119]:
C

array([[5675,   66,    0,    0],
       [   2, 1104,    0,    0],
       [ 213,  868,  762,  356],
       [   5,    1,   16,   15]], dtype=int64)

In [133]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
qda = QuadraticDiscriminantAnalysis()
qda.fit(X_train,y_train) 

y_pred = qda.predict(X_test)
y_pred_prob = qda.predict_proba(X_test)[::,0]
print(classification_report(y_test,y_pred))
C = confusion_matrix(y_test,y_pred)
for i in range(4):
    fpr, acc, dr = perf_measure_class(C, i)
    print("class "+str(i)+": "+"fpr: "+str(fpr)+" acc: "+str(acc)+" dr: "+str(dr))


             precision    recall  f1-score   support

          0       0.92      0.91      0.92      5741
          1       0.38      0.61      0.46      1106
          2       0.71      0.42      0.53      2199
          3       0.07      0.65      0.13        37

avg / total       0.80      0.75      0.76      9083

class 0: fpr: 0.13046080191502094 acc: 0.89639986788506 dr: 0.9120362306218429
class 1: fpr: 0.1395261376457315 acc: 0.8295717274028405 dr: 0.6066907775768535
class 2: fpr: 0.054038349796629866 acc: 0.8182318617196961 dr: 0.4183719872669395
class 3: fpr: 0.03437983639177537 acc: 0.9643289662005945 dr: 0.6486486486486487


C:\Users\Nishant\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:682: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


In [134]:
C

array([[5236,  146,  359,    0],
       [ 435,  671,    0,    0],
       [   1,  967,  920,  311],
       [   0,    0,   13,   24]], dtype=int64)

# Adversarial classification

In [67]:
import pickle
with open('Adv_sample.pkl','rb') as f:
    x_adv=pickle.load(f)

In [68]:
x_adv

array([[0.        , 0.        , 0.        , ..., 0.        , 0.0035203 ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.98855877, 0.15069449, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.11555127, 0.11555127, 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [69]:
x_adv.shape

(23516, 36)

In [70]:
#import its corresponding label
with open('y_test_adv.pkl','rb') as f:
    y_test_adv=pickle.load(f)

In [72]:
y_test_adv

125001        dos
125002     normal
125003        dos
125004     normal
125005     normal
125006     normal
125007     normal
125008        dos
125009     normal
125010     normal
125011     normal
125012        dos
125013     normal
125014        dos
125015        dos
125016     normal
125017     normal
125018      probe
125019        dos
125020     normal
125021     normal
125022      probe
125023     normal
125024        dos
125025     normal
125026     normal
125027     normal
125028     normal
125029     normal
125030     normal
           ...   
22514      normal
22515     unknown
22516      normal
22517     unknown
22518      normal
22519     unknown
22520       probe
22521       probe
22522         dos
22523      normal
22524         u2r
22525     unknown
22526      normal
22527      normal
22528         dos
22529      normal
22530         dos
22531         dos
22532      normal
22533      normal
22534         dos
22535      normal
22536         dos
22537     unknown
22538     

In [73]:
y_test_adv=y_test_adv.reset_index(drop=True)

In [74]:
y_test_adv

0            dos
1         normal
2            dos
3         normal
4         normal
5         normal
6         normal
7            dos
8         normal
9         normal
10        normal
11           dos
12        normal
13           dos
14           dos
15        normal
16        normal
17         probe
18           dos
19        normal
20        normal
21         probe
22        normal
23           dos
24        normal
25        normal
26        normal
27        normal
28        normal
29        normal
          ...   
23486     normal
23487    unknown
23488     normal
23489    unknown
23490     normal
23491    unknown
23492      probe
23493      probe
23494        dos
23495     normal
23496        u2r
23497    unknown
23498     normal
23499     normal
23500        dos
23501     normal
23502        dos
23503        dos
23504     normal
23505     normal
23506        dos
23507     normal
23508        dos
23509    unknown
23510        dos
23511     normal
23512     normal
23513        d

In [75]:
#get index of unknown and normal
index_normal=list((y_test_adv.loc[y_test_adv.values=='normal'].index))
index_unknown=list((y_test_adv.loc[y_test_adv.values=='unknown'].index))

In [76]:
index_normal

[1,
 3,
 4,
 5,
 6,
 8,
 9,
 10,
 12,
 15,
 16,
 19,
 20,
 22,
 24,
 25,
 26,
 27,
 28,
 29,
 31,
 32,
 33,
 34,
 35,
 36,
 41,
 43,
 44,
 46,
 47,
 51,
 54,
 56,
 57,
 59,
 60,
 61,
 63,
 64,
 70,
 72,
 74,
 75,
 77,
 79,
 80,
 81,
 87,
 88,
 91,
 92,
 95,
 96,
 100,
 102,
 106,
 107,
 110,
 111,
 112,
 119,
 120,
 121,
 122,
 128,
 131,
 132,
 133,
 135,
 137,
 138,
 139,
 140,
 143,
 145,
 146,
 147,
 149,
 153,
 154,
 155,
 156,
 157,
 159,
 160,
 162,
 165,
 166,
 167,
 171,
 173,
 174,
 176,
 177,
 180,
 182,
 186,
 190,
 191,
 192,
 193,
 196,
 198,
 199,
 202,
 203,
 204,
 205,
 206,
 209,
 210,
 211,
 215,
 217,
 218,
 219,
 220,
 221,
 224,
 226,
 227,
 229,
 231,
 232,
 234,
 235,
 236,
 237,
 240,
 241,
 242,
 244,
 246,
 247,
 248,
 249,
 251,
 252,
 253,
 256,
 257,
 258,
 259,
 260,
 261,
 263,
 266,
 267,
 270,
 271,
 273,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 287,
 289,
 290,
 291,
 292,
 295,
 296,
 297,
 298,
 299,
 302,
 303,
 304,
 306,
 307,
 308,
 310,

In [77]:
index_unknown

[976,
 977,
 983,
 994,
 1003,
 1008,
 1021,
 1030,
 1031,
 1039,
 1050,
 1060,
 1066,
 1079,
 1085,
 1086,
 1092,
 1105,
 1107,
 1110,
 1111,
 1117,
 1119,
 1122,
 1126,
 1129,
 1143,
 1147,
 1150,
 1164,
 1172,
 1173,
 1175,
 1180,
 1183,
 1192,
 1204,
 1209,
 1211,
 1212,
 1215,
 1229,
 1249,
 1256,
 1262,
 1264,
 1265,
 1269,
 1301,
 1313,
 1314,
 1319,
 1321,
 1342,
 1354,
 1356,
 1363,
 1366,
 1380,
 1381,
 1386,
 1391,
 1399,
 1405,
 1407,
 1421,
 1424,
 1431,
 1432,
 1444,
 1451,
 1455,
 1459,
 1466,
 1469,
 1475,
 1482,
 1485,
 1486,
 1490,
 1504,
 1505,
 1525,
 1537,
 1547,
 1555,
 1562,
 1564,
 1566,
 1573,
 1576,
 1581,
 1597,
 1602,
 1606,
 1614,
 1616,
 1624,
 1629,
 1650,
 1652,
 1658,
 1659,
 1673,
 1700,
 1705,
 1708,
 1711,
 1714,
 1725,
 1727,
 1738,
 1746,
 1760,
 1771,
 1772,
 1778,
 1781,
 1783,
 1785,
 1788,
 1805,
 1808,
 1817,
 1818,
 1824,
 1829,
 1838,
 1841,
 1843,
 1850,
 1854,
 1864,
 1867,
 1868,
 1873,
 1877,
 1889,
 1896,
 1903,
 1909,
 1912,
 1913,
 19

In [78]:
index_total=(index_normal+index_unknown)

In [79]:
index_total

[1,
 3,
 4,
 5,
 6,
 8,
 9,
 10,
 12,
 15,
 16,
 19,
 20,
 22,
 24,
 25,
 26,
 27,
 28,
 29,
 31,
 32,
 33,
 34,
 35,
 36,
 41,
 43,
 44,
 46,
 47,
 51,
 54,
 56,
 57,
 59,
 60,
 61,
 63,
 64,
 70,
 72,
 74,
 75,
 77,
 79,
 80,
 81,
 87,
 88,
 91,
 92,
 95,
 96,
 100,
 102,
 106,
 107,
 110,
 111,
 112,
 119,
 120,
 121,
 122,
 128,
 131,
 132,
 133,
 135,
 137,
 138,
 139,
 140,
 143,
 145,
 146,
 147,
 149,
 153,
 154,
 155,
 156,
 157,
 159,
 160,
 162,
 165,
 166,
 167,
 171,
 173,
 174,
 176,
 177,
 180,
 182,
 186,
 190,
 191,
 192,
 193,
 196,
 198,
 199,
 202,
 203,
 204,
 205,
 206,
 209,
 210,
 211,
 215,
 217,
 218,
 219,
 220,
 221,
 224,
 226,
 227,
 229,
 231,
 232,
 234,
 235,
 236,
 237,
 240,
 241,
 242,
 244,
 246,
 247,
 248,
 249,
 251,
 252,
 253,
 256,
 257,
 258,
 259,
 260,
 261,
 263,
 266,
 267,
 270,
 271,
 273,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 287,
 289,
 290,
 291,
 292,
 295,
 296,
 297,
 298,
 299,
 302,
 303,
 304,
 306,
 307,
 308,
 310,

In [80]:
len(index_total)

13993

In [81]:
#delete normal and unkown from y_adv_test
y_test_adv=y_test_adv[y_test_adv.values!='unknown']
y_test_adv=y_test_adv[y_test_adv.values!='normal']

In [82]:
y_test_adv.shape

(9523,)

In [83]:
y_test_adv=y_test_adv.apply(bool_attack)

In [84]:
y_test_adv

0        0
2        0
7        0
11       0
13       0
14       0
17       1
18       0
21       1
23       0
30       0
37       1
38       0
39       0
40       0
42       0
45       0
48       0
49       0
50       0
52       0
53       0
55       0
58       0
62       0
65       2
66       0
67       0
68       1
69       1
        ..
23444    0
23445    0
23449    0
23454    1
23455    0
23457    0
23458    2
23462    2
23465    1
23468    0
23469    0
23470    0
23472    0
23473    2
23475    1
23477    0
23482    0
23484    0
23485    2
23492    1
23493    1
23494    0
23496    3
23500    0
23502    0
23503    0
23506    0
23508    0
23510    0
23513    0
Name: unknown1, Length: 9523, dtype: int64

In [85]:
#delete corresponding row from x_adv
#x = numpy.delete(x, (0), axis=0)
x_adv=np.delete(x_adv,index_total,axis=0)

In [87]:
x_adv.shape # and y_test_adv

(9523, 36)

In [88]:
#predict RF
y_pred_adv = rf.predict(x_adv)

In [89]:
y_pred_adv

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [90]:
np.array(y_test_adv)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [91]:
print(classification_report(y_test_adv,y_pred_adv))
C_adv = confusion_matrix(y_test_adv,y_pred_adv)

             precision    recall  f1-score   support

          0       0.99      0.95      0.97      6099
          1       0.43      1.00      0.60      1183
          2       0.97      0.40      0.56      2204
          3       0.25      0.30      0.27        37

avg / total       0.92      0.82      0.83      9523



In [92]:
C_adv

array([[5769,  318,   12,    0],
       [   1, 1182,    0,    0],
       [  29, 1270,  872,   33],
       [   3,    9,   14,   11]], dtype=int64)

In [93]:
for i in range(4):
    fpr, acc, dr = perf_measure_class(C_adv, i)
    print("class "+str(i)+": "+"fpr: "+str(fpr)+" acc: "+str(acc)+" dr: "+str(dr))

class 0: fpr: 0.009637850467289719 acc: 0.9618817599495957 dr: 0.9458927693064437
class 1: fpr: 0.19148681055155875 acc: 0.8321957366376141 dr: 0.9991546914623838
class 2: fpr: 0.003552397868561279 acc: 0.8573978788196996 dr: 0.3956442831215971
class 3: fpr: 0.003478810879190386 acc: 0.9938044733802374 dr: 0.2972972972972973


In [98]:
#predict for adaboost
y_pred_adv = ada.predict(x_adv)

In [99]:
y_pred_adv

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [100]:
print(classification_report(y_test_adv,y_pred_adv))
C_adv = confusion_matrix(y_test_adv,y_pred_adv)

             precision    recall  f1-score   support

          0       0.78      0.95      0.85      6099
          1       0.53      0.60      0.56      1183
          2       0.95      0.29      0.45      2204
          3       0.07      0.03      0.04        37

avg / total       0.78      0.75      0.72      9523



In [101]:
C_adv

array([[5798,  294,    7,    0],
       [ 470,  712,    0,    1],
       [1203,  341,  648,   12],
       [   5,    3,   28,    1]], dtype=int64)

In [102]:
for i in range(4):
    fpr, acc, dr = perf_measure_class(C_adv, i)
    print("class "+str(i)+": "+"fpr: "+str(fpr)+" acc: "+str(acc)+" dr: "+str(dr))

class 0: fpr: 0.49007009345794394 acc: 0.7921873359235535 dr: 0.9506476471552714
class 1: fpr: 0.07649880095923262 acc: 0.8835451013336133 dr: 0.6018596787827557
class 2: fpr: 0.00478207405383249 acc: 0.832930799117925 dr: 0.294010889292196
class 3: fpr: 0.0013704406493780308 acc: 0.9948545626378242 dr: 0.02702702702702703


In [106]:
#predict for GNB
y_pred_adv = gnb.predict(x_adv)

In [107]:
y_pred_adv

array([0, 0, 0, ..., 0, 0, 3], dtype=int64)

In [108]:
print(classification_report(y_test_adv,y_pred_adv))
C_adv = confusion_matrix(y_test_adv,y_pred_adv)

             precision    recall  f1-score   support

          0       0.85      0.67      0.75      6099
          1       0.17      0.46      0.24      1183
          2       0.48      0.15      0.23      2204
          3       0.03      0.49      0.05        37

avg / total       0.68      0.52      0.56      9523



In [109]:
for i in range(4):
    fpr, acc, dr = perf_measure_class(C_adv, i)
    print("class "+str(i)+": "+"fpr: "+str(fpr)+" acc: "+str(acc)+" dr: "+str(dr))

class 0: fpr: 0.21436915887850466 acc: 0.7124855612727082 dr: 0.6714215445154943
class 1: fpr: 0.33057553956834534 acc: 0.6438097238265252 dr: 0.463229078613694
class 2: fpr: 0.04905041672359612 acc: 0.7660401134096398 dr: 0.15199637023593465
class 3: fpr: 0.07136833227914822 acc: 0.9269137876719521 dr: 0.4864864864864865


In [113]:
#predict for KNN
y_pred_adv = neigh.predict(x_adv)

In [114]:
y_pred_adv

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [115]:
print(classification_report(y_test_adv,y_pred_adv))
C_adv = confusion_matrix(y_test_adv,y_pred_adv)

             precision    recall  f1-score   support

          0       0.89      0.84      0.87      6099
          1       0.29      0.82      0.43      1183
          2       0.88      0.11      0.20      2204
          3       0.16      0.27      0.20        37

avg / total       0.81      0.67      0.65      9523



In [116]:
C

array([[5607,  130,    4,    0],
       [  41, 1065,    0,    0],
       [ 454, 1377,  294,   74],
       [   2,   10,    8,   17]], dtype=int64)

In [117]:
for i in range(4):
    fpr, acc, dr = perf_measure_class(C_adv, i)
    print("class "+str(i)+": "+"fpr: "+str(fpr)+" acc: "+str(acc)+" dr: "+str(dr))

class 0: fpr: 0.19129672897196262 acc: 0.8317757009345794 dr: 0.8447286440400066
class 1: fpr: 0.2881294964028777 acc: 0.7250866323637509 dr: 0.8182586644125106
class 2: fpr: 0.004645443366580134 acc: 0.7910322377402079 dr: 0.11252268602540835
class 3: fpr: 0.005587181109002741 acc: 0.9915992859393048 dr: 0.2702702702702703


In [127]:
#predict for dt
y_pred_adv = dt.predict(x_adv)


In [130]:
print(classification_report(y_test_adv,y_pred_adv))
C_adv = confusion_matrix(y_test_adv,y_pred_adv)

             precision    recall  f1-score   support

          0       0.96      0.83      0.89      6099
          1       0.36      0.91      0.52      1183
          2       0.86      0.35      0.50      2204
          3       0.04      0.38      0.07        37

avg / total       0.86      0.73      0.75      9523



In [131]:
C_adv

array([[5049,  962,   63,   25],
       [  43, 1082,   49,    9],
       [ 181,  926,  770,  327],
       [   5,    2,   16,   14]], dtype=int64)

In [132]:
for i in range(4):
    fpr, acc, dr = perf_measure_class(C_adv, i)
    print("class "+str(i)+": "+"fpr: "+str(fpr)+" acc: "+str(acc)+" dr: "+str(dr))

class 0: fpr: 0.06688084112149532 acc: 0.8656935839546361 dr: 0.8278406296114117
class 1: fpr: 0.22661870503597123 acc: 0.7909272288144492 dr: 0.9146238377007607
class 2: fpr: 0.01748872796830168 acc: 0.835976057964927 dr: 0.34936479128856623
class 3: fpr: 0.038056082648113006 acc: 0.9596765725086632 dr: 0.3783783783783784


In [135]:
#predict for QDA
y_pred_adv = qda.predict(x_adv)
print(classification_report(y_test_adv,y_pred_adv))
C_adv = confusion_matrix(y_test_adv,y_pred_adv)
for i in range(4):
    fpr, acc, dr = perf_measure_class(C_adv, i)
    print("class "+str(i)+": "+"fpr: "+str(fpr)+" acc: "+str(acc)+" dr: "+str(dr))

             precision    recall  f1-score   support

          0       0.92      0.63      0.75      6099
          1       0.20      0.74      0.31      1183
          2       0.69      0.24      0.36      2204
          3       0.08      0.35      0.13        37

avg / total       0.77      0.55      0.60      9523

class 0: fpr: 0.09550233644859812 acc: 0.7261367216213378 dr: 0.6260042629939334
class 1: fpr: 0.42697841726618707 acc: 0.5936154573138717 dr: 0.738799661876585
class 2: fpr: 0.033064626315070365 acc: 0.7992229339493857 dr: 0.2422867513611615
class 3: fpr: 0.016234450769555132 acc: 0.9813084112149533 dr: 0.35135135135135137


In [136]:
C_adv

array([[3818, 2053,  228,    0],
       [ 304,  874,    5,    0],
       [  23, 1493,  534,  154],
       [   0,   15,    9,   13]], dtype=int64)